package com.orderingsystem.order.domain.model.outbox;

public enum MessageType {
    PAYMENT_COMPLETE, PAYMENT_ROLLBACK, RESTAURANT_ACCEPT, RESTAURANT_DECLINE, RESTAURANT_APPROVAL, RESTAURANT_REJECT, CUSTOMER_CREATE, COUPON_COMPLETE, CUSTOMER_DELETE
}
