services:
  kafka-1:
    image: bitnami/kafka:${KAFKA_VERSION}
    hostname: kafka-1
    ports:
      - "19092:19092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL://:19092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka-1:9092,EXTERNAL://localhost:19092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - "./volumes/kafka/broker-1:/bitnami/kafka"
    depends_on:
      - zookeeper
    networks:
      - ${GLOBAL_NETWORK:-kafka}

  kafka-2:
    image: bitnami/kafka:${KAFKA_VERSION}
    hostname: kafka-2
    ports:
      - "29092:29092"
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka-2:9092,EXTERNAL://localhost:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - ./volumes/kafka/broker-2:/bitnami/kafka
    depends_on:
      - zookeeper
    networks:
      - ${GLOBAL_NETWORK:-kafka}

  kafka-3:
    image: bitnami/kafka:${KAFKA_VERSION}
    hostname: kafka-3
    ports:
      - "39092:39092"
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL://:39092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka-3:9092,EXTERNAL://localhost:39092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - ./volumes/kafka/broker-3:/bitnami/kafka
    depends_on:
      - zookeeper
    networks:
      - ${GLOBAL_NETWORK:-kafka}

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "9000:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: kafka-local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:9092,kafka-2:9092,kafka-3:9092
    networks:
      - ${GLOBAL_NETWORK:-kafka}

#debezium connector
  debezium-connector:
    image: debezium/connect:${DEBEZIUM_VERSION}
    platform: linux/amd64
    ports:
      - 8083:8083
    environment:
      GROUP_ID: "1"
      CONFIG_STORAGE_TOPIC: "connect-config"
      OFFSET_STORAGE_TOPIC: "connect-offsets"
      STATUS_STORAGE_TOPIC: "connect-status"
      BOOTSTRAP_SERVERS: kafka-1:9092,kafka-2:9092,kafka-3:9092
      LOGGING_LEVEL: "DEBUG"
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_PLUGIN_PATH: /kafka/connect/debezium-plugins
    depends_on:
    - kafka-1
    - kafka-2
    - kafka-3
    volumes:
      - ${DEBEZIUM_VOLUMES}
    networks:
      - ${GLOBAL_NETWORK:-kafka}
